//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Api_EPamphalet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertisement
    {
        public int Advert_id { get; set; }
        public string Advert_text { get; set; }
        public string Advert_image { get; set; }
        public Nullable<int> FKvendor_id { get; set; }
    
        public virtual Vendor Vendor { get; set; }
    }
}
