//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Api_EPamphalet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Choices = new HashSet<Choice>();
        }
    
        public int Customer_id { get; set; }
        public string Customer_username { get; set; }
        public string Customer_name { get; set; }
        public string Customer_password { get; set; }
    
        public virtual ICollection<Choice> Choices { get; set; }
    }
}
