//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Api_EPamphalet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fence
    {
        public int Fence_id { get; set; }
        public string Fence_name { get; set; }
        public Nullable<decimal> Fence_longitude { get; set; }
        public Nullable<decimal> Fence_latitude { get; set; }
        public Nullable<int> FKvendor_id { get; set; }
        public Nullable<double> Fence_radius { get; set; }
    
        public virtual Vendor Vendor { get; set; }
    }
}
