//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Api_EPamphalet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reference
    {
        public decimal Reference_no { get; set; }
        public string SalesCheck { get; set; }
        public Nullable<System.DateTime> Date_time { get; set; }
        public Nullable<int> FKadvert_id { get; set; }
        public Nullable<int> FKcustomer_id { get; set; }
    }
}
