//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Api_EPamphalet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        public Vendor()
        {
            this.Advertisements = new HashSet<Advertisement>();
            this.Choices = new HashSet<Choice>();
            this.Fences = new HashSet<Fence>();
        }
    
        public int Vendor_id { get; set; }
        public string Vendor_name { get; set; }
        public string Vendor_password { get; set; }
        public string Vendor_phone { get; set; }
        public string Vendor_address { get; set; }
    
        public virtual ICollection<Advertisement> Advertisements { get; set; }
        public virtual ICollection<Choice> Choices { get; set; }
        public virtual ICollection<Fence> Fences { get; set; }
    }
}
